mariadb:
  enabled: true
  image:
    repository: mariadb
    tag: latest
  
  # env var
  rootPassword: "veryS3c3u!@#"
  database: sang-test
  user: sangnn
  password: "sangnn@123"

  # values for ConfigMap
  config:
    max_connections: 200
    max_allowed_packet: 64M

  config_files:
    my1.cnf: |
      [mysql]
      default-character-set = utf8

    my2.cnf: |
      [mysqld]
      innodb_buffer_pool_size = 256M

  backup:
    enabled: false
    schedule: "0 3 * * *"
    backup_mariadb_user: "mariadb-backup-user"
    backup_mariadb_password: "mariadb-backup-password"
    storage:
      type: s3
      s3:
        access_id: "your-access-id"
        secret_key: "your-secret-key"
        region: "ap-southeast-1"
        bucket: "my-backup-bucket"
        path: "backup-directory"
        endpoint_override: "" # use this if you're using some S3-compatible endpoints (not AWS)

  exporter:
    enabled: false
    image:
      repository: prom/mysqld-exporter
      tag: latest
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "200m"
        memory: "200Mi"
    metricsPort: 9104
    initUser: true              # will help create exporter user at start of the Mariadb container
    mysqlUser: exporter         # if you specify yours, set `initUser: false`
    mysqlPassword: Aa@1234567   # same as above

phpmyadmin:
  enabled: true
  image:
    repository: phpmyadmin
    tag: latest
  service:
    type: ClusterIP

  ingress:
    enabled: true
    hostname: "phpmyadmin.28.sohan.cloud"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls:
      enabled: true
      secretName: "phpmyadmin-tls"

  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
    limits:
      cpu: "200m"
      memory: "200Mi"

  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    averageUtilizationCPU: 50
    averageUtilizationMemory: 80
