mariadb:
  enabled: true
  image:
    repository: mariadb
    tag: latest
  
  # env var
  rootPassword: "veryS3c3u!@#"
  database: sang-test
  user: sangnn
  password: "sangnn@123"

  # values for ConfigMap
  config:
    max_connections: 200
    max_allowed_packet: 64M

  config_files:
    my1.cnf: |
      [mysql]
      default-character-set = utf8

    my2.cnf: |
      [mysqld]
      innodb_buffer_pool_size = 256M


phpmyadmin:
  enabled: true
  image:
    repository: phpmyadmin
    tag: latest
  service:
    type: ClusterIP

  ingress:
    enabled: true
    hostname: "phpmyadmin.28.sohan.cloud"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls:
      enabled: true
      secretName: "phpmyadmin-tls"

  resources:
    requests:
      cpu: "10m"
      memory: "20Mi"
    limits:
      cpu: "50m"
      memory: "50Mi"
