{{- if and .Values.mariadb.backup.enabled (eq .Values.mariadb.backup.storage.type "s3") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-phpmyadmin.fullname" . }}-aws-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.mariadb.backup.storage.s3.access_id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.mariadb.backup.storage.s3.secret_key | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ .Values.mariadb.backup.storage.s3.region | b64enc | quote }}
  {{- if .Values.mariadb.backup.storage.s3.endpoint_override }}
  AWS_ENDPOINT_OVERRIDE: {{ .Values.mariadb.backup.storage.s3.endpoint_override | b64enc | quote }}
  {{- end }}
{{- end }}
