apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb-phpmyadmin.fullname" . }}-mariadb
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: {{ include "mariadb-phpmyadmin.name" . }}-mariadb

