apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-phpmyadmin.fullname" . }}-credentials-secret
type: Opaque
data:
  # Base64 encode the values for Kubernetes Secrets
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | b64enc | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | b64enc | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | b64enc | quote }}
