apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mariadb-phpmyadmin.fullname" . }}-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mariadb-phpmyadmin.name" . }}-mariadb
  template:
    metadata:
      labels:
        app: {{ include "mariadb-phpmyadmin.name" . }}-mariadb
    spec:
      containers:
      - name: mariadb
        image: {{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "mariadb-phpmyadmin.fullname" . }}-credentials-secret
                key: MARIADB_ROOT_PASSWORD
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ include "mariadb-phpmyadmin.fullname" . }}-credentials-secret
                key: MARIADB_DATABASE
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "mariadb-phpmyadmin.fullname" . }}-credentials-secret
                key: MARIADB_USER
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "mariadb-phpmyadmin.fullname" . }}-credentials-secret
                key: MARIADB_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: config-volume
            mountPath: /etc/mysql/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "mariadb-phpmyadmin.fullname" . }}-config
