{{- if .Values.mariadb.exporter.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb-phpmyadmin.fullname" . }}-exporter-config
data:
  .my.cnf: |
    [client]
    user={{ .Values.mariadb.exporter.mysqlUser }}
    password={{ .Values.mariadb.exporter.mysqlPassword }}
{{- end}}