apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb-phpmyadmin.fullname" . }}-phpmyadmin
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ include "mariadb-phpmyadmin.name" . }}-phpmyadmin

