name: Helm Chart CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: latest

    - name: Lint and Test Helm Chart
      run: |
        helm lint ./mariadb-phpmyadmin
        helm template ./mariadb-phpmyadmin --values ./mariadb-phpmyadmin/values.yaml --debug

    - name: Package Helm Chart
      run: |
        helm package ./mariadb-phpmyadmin --destination ./charts
      if: github.event_name != 'pull_request'

    - name: Push Helm Chart to ghcr.io
      run: |
        echo "${{ secrets.TOKEN }}" |  helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
        helm push ./charts/mariadb-phpmyadmin-*.tgz oci://ghcr.io/${{ github.actor }}
      if: github.event_name != 'pull_request'

